# Generated by Django 3.2.11 on 2022-02-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_is_dead_profile'),
        ('post', '0006_post_memory_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user_profile.userprofile'),
            preserve_default=False,
        ),
    ]
