# Generated by Django 3.2.11 on 2022-02-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_is_dead_profile'),
        ('post', '0007_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_profile.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='user_profile.userprofile'),
            preserve_default=False,
        ),
    ]
