# Generated by Django 3.2.11 on 2022-02-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20220129_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_dead_profile',
            field=models.BooleanField(default=False),
        ),
    ]
