# Generated by Django 3.2.11 on 2022-02-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0006_userprofile_is_dead_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trusted_users', models.ManyToManyField(blank=True, related_name='trusted_user_access', to='user_profile.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
    ]
